CREATE TABLE Series (
    TITULO VARCHAR,
    ID_SERIES INTEGER PRIMARY KEY,
    DESCRICAO VARCHAR,
    TEMA VARCHAR,
    GENERO VARCHAR,
    ANOLANCAMENTO INTEGER,
    TEMPORADAS INTEGER,
    EXCLUIDO BIT,
    fk_DIRETOR_CPF INTEGER
);

CREATE TABLE DIRETOR (
    ID_DIRETOR INTEGER PRIMARY KEY,
    DATANASCIMENTO DATE,
    NACIONALIDADE VARCHAR
);
 
ALTER TABLE Series ADD CONSTRAINT FK_Series_2
    FOREIGN KEY (fk_DIRETOR_CPF)
    REFERENCES DIRETOR (ID_DIRETOR)
    ON DELETE RESTRICT;